apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: spring-app
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001